### ISSUE TITLE
Logo offer for MovieFinderOmdb

### ISSUE THREAD

**Issue by familqasimov** [Tobibur/MovieFinderOmdb#2]
Hi sir. I would like to offer logo. If you like I can give you all the formats of the design free. If you want a change please specify or select one of them. 

![untitled-1](https://user-images.githubusercontent.com/36432269/42046662-6b508c02-7b0f-11e8-8ac0-a3fd9fee4d8c.png)

Best regard
Famil Qasimov

**Comment by Tobibur** [comment]
I like your logos.. Its really nice.. I like 4 and 9 though all of them are great.. Thanks Famil.. you can make the changes.. fork this project and send a pull request..
